name: ui_ecommerce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 6.3.0+64
environment:
  sdk: ^3.6.0
  # sdk: '>=3.4.0-190.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  motion_tab_bar_v2: ^0.3.0
  dots_indicator: ^3.0.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.3.5
  dart_jsonwebtoken: ^2.14.2
  loading_animation_widget: ^1.3.0
  font_awesome_flutter: ^10.8.0
  dropdown_button2: ^2.3.9
  easy_autocomplete: ^1.6.0
  animated_bottom_navigation_bar: ^1.3.3
  curved_labeled_navigation_bar: ^2.0.5
  photo_view: ^0.15.0
  flutter_spinkit: ^5.2.1
  textfield_search: ^0.11.1
  url_launcher: ^6.3.1
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  badges: ^3.1.2
  flutter_notification_manager: ^1.0.0
  # flutter_app_badger: ^1.5.0
  flutter_dialogs: ^3.0.0
  intl: ^0.20.1
  video_player: ^2.9.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.16
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  flutter_typeahead: ^5.2.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appcbc.jpg"
  image_path_ios: "assets/images/appcbc.jpg"

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/images/icons/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal.ttf
